config/routes.rb
Rails.application.routes.draw do
  resources :cities
  get 'students/check_email_presence'
  resources :courses
  resources :instructors
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
has_many :registrations
has_many :courses,through: :registrations
validates_presence_of :name,:email,:major,:dob
validates_uniqueness_of :email
belongs_to :city
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    @student = Student.new
    @city=City.new
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student =Student.find(params[:id])
  end

  # GET /students/new
  def new
    @student = Student.new
    @city=City.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        format.js 
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.js 
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = student.find(params[:id])
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_email_presence
     @email = Student.find_by(email: params[:email])
     render json: @email.nil? ? {'msg': true} : {'msg': false} 
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :email, :major,:dob,:city_id, :course_ids)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_errors.html.erb
<div class = "alert alert-danger">
	<%if(@student.errors.any?)%>
	<ol>
	<%@student.errors.full_messages.each do |msg,index|%>
	  <li><%=msg%></li>
	<%end%>
	</ol>
<%else%>
   
<%end%>
</div>

app/views/students/_form.html.erb
<%= form_for(student, id: "new_student_form",remote: true) do |form| %>
<div id="student_form_errors">
</div>  

<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name, id: :student_name,class: "form-control" %>
  <span id = 'nameError'></span>
</div>



<div class="form-group">
  <%= form.label :email %>
  <%= form.text_field :email, id: :student_email,class: "form-control" %>
  <span id = 'emailError'></span>
</div>

<div class="form-group">
  <%= form.label :major %>
  <%= form.text_field :major, id: :student_major,class: "form-control" %>
  <span id = 'majorError'></span>
</div>


<div class="form-group">
  <%= form.label :dob %>
  <%= form.date_select :dob, id: :student_dob,class: "form-control" %>
  <span id = 'dobError'></span>
</div>

<div class= "form-group">
<h3>Select Courses</h3>
<%= form.collection_select :course_ids,Course.all,:id,:name,{prompt: "enter the courses to be selected"},{multiple: true,id: "student_course_ids"}%>
</div>

<div class = form-group>
  <h3>Select the cityname</h3>
  <%=form.label  :city_id%>
  <%=form.collection_select :city_id,City.all,:id,:name,{prompt: "Select the city"}, { id: :student_city_id} %>
  <button type="button" class="btn btn-link" data-toggle="modal" data-target="#exampleModal">Add City</button>

<%= form.submit "Submit the Details",id:"submit_details"%>
</div>
<%end %>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Type the new city</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <%=render '/cities/form',city: @city%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>



 <script type="text/javascript">
  $("#student_course_ids").chosen({disable_search_threshold: 10});
</script> 
<script>
 var formHandle=document.getElementById('new_student_form');
 var resetHandle=document.getElementById('student_reset');
 var nameHandle = document.getElementById('student_name');
 var emailHandle = document.getElementById('student_email');
 var majorHandle = document.getElementById('student_major');
 var dobHandle = document.getElementById('student_dob');
 var submitHandle = document.getElementById('submit_details');

 var nameErrorHandle = document.getElementById('nameError');
 var emailErrorHandle = document.getElementById('emailError');
 var majorErrorHandle = document.getElementById('majorError');
 var dobErrorHandle = document.getElementById('dobError');

 var nameRegex=/^[a-zA-Z]+$/;
 var emailRegex=/.*@[a-z0-9.-]*/i;
 var majorRegex = /^[a-zA-Z]+$/;
 var validator={
  nameValid: false,
  nameValid: false,
  emailValid: false,
  majorValid: false,
}

nameHandle.addEventListener('blur',function(){
  if(nameHandle.value === ""){
   validator.nameValid= false;
   $('#student_name')[0].attributes[1].value="form-control is-invalid"
   nameErrorHandle.innerHTML = 'the name can\'t be blank';
   console.log(validator);
 }
 else if((nameHandle.value !== "")&&(nameRegex.test(nameHandle.value))){
  validator.nameValid = true;
  nameErrorHandle.innerHTML = 'thee name is valid';
  $('#student_name')[0].attributes[1].value="form-control is-valid"
}
else{
  validator.nameValid = false;  
  nameErrorHandle.innerHTML = 'the name is not a vaid one';
  $('#student_name')[0].attributes[1].value="form-control is-invalid";
}    
},false)



emailHandle.addEventListener('blur',function(){
  if(emailHandle.value === ""){
   validator.emailValid = false;
   emailErrorHandle.innerHTML = 'the email cant be blank!';
   $('#student_email')[0].attributes[1].value="form-control is-invalid";
  
 }
 else if((emailHandle.value != "")&&(emailRegex.test(emailHandle.value))){
   var xhr = new XMLHttpRequest();
   xhr.open('GET',`/students/check_email_presence?email=${emailHandle.value}`,true);
   xhr.onreadystatechange=function(){
    if((xhr.status === 200)&&(xhr.readyState === 4)){
     var response = JSON.parse(xhr.responseText);
     if(response.msg === true){
      emailErrorHandle.innerHTML = 'the email can be taken';
      validator.emailValid = true;
      console.log(`email check ${validator}`);
      $('#student_name')[0].attributes[1].value="form-control is-valid"
      
    }
    else{
      emailErrorHandle.innerHTML = 'the email is not a valid one';
      console.log(`email is not a valid one ${validator.values}`);
      validator.emailValid = false;
      $('#student_email')[0].attributes[1].value="form-control is-invalid"
    }
  }
}
xhr.send();
}
else{
 validator.emailValid = false;
 emailErrorHandle.innerHTML = 'the email is not a valid one';
 $('#student_email')[0].attributes[1].value="form-control is-invalid"
}
},false)

majorHandle.addEventListener('blur',function(){
  if(majorHandle.value === ""){
    validator.majorValid = false;
    majorErrorHandle.innerHTML = "the major cant be blank";
   $('#student_major')[0].attributes[1].value="form-control is-invalid";

  }
  else if((majorHandle.value != "")&&(majorRegex.test(majorHandle.value))) {
    validator.majorValid = true;
    majorErrorHandle.innerHTML = 'the major is a valid one';
    $('#student_major')[0].attributes[1].value="form-control is-valid";
  }
  else{
    validator.majorValid = false;
    majorErrorHandle.innerHTML = 'the major is not a valid one'
    $('#student_major')[0].attributes[1].value="form-control is-invalid";
  }
},false)


resetHandle.addEventListener('click',function(e){
  e.preventDefault();
  formHandle.reset();
},false)

/*   formHandle.addEventListener('submit',function(e){
     if(Object.values(validator).includes(false)){
         e.preventDefault();
         setTimeout(function(){
             submitHandle.disabled = false;
             console.log(`${validator.values}`);
         },500)       
     }
     else{
        submitHandle.disabled = false;
        formHandle.reset(); 
     }
   },false) */


 </script>  

app/views/students/_student.html.erb
<div class="row" >
   <div class = "col-md-3">
     <div class="card">
     <img class="card-img-top" src="http://www.acfe.com/uploadedImages/ACFE_Website/Content/images/membership-certification/graduate-member.jpg" alt="Card image cap">
     <div class="card-block">
        <h4 class="card-title"><%= @student.name%></h4>	
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted"><%=@student.created_at%></small></p>
        <%= link_to "Register","/students/new",class: "btn btn-primary" %>
        <span class = "float-right">Number of courses taken :<%= @student.courses.count%>  </span>
     </div>
     </div>
   </div>
</div>

app/views/students/create.js.erb
<% if(@student.errors.any?)%>
   $('#student_form_errors').html('');
   $('#student_form_errors').append('<%= escape_javascript render 'errors'%>');
<% else %>

   $('#student_form_errors').hide();
   $('#new_student_form').modal('hide');// this does the work of the hiding he form when there are no errors in the form
   $('#studentsList').prepend('<%= escape_javascript render 'student'%>');    
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>
<%arr1=(((Date.today-30.years).year)..((Date.today-18.years).year)).to_a
hash_of_year={}
hash_of_month={}
arr2=["JAN","FEB","MARCH","April","MAY","June","July","Aug","Sep","Oct",
  "Nov","DEC"]
number=1%>

<%arr1.each do |yer|%>
   <%hash_of_year[yer]=Student.all.pluck(:dob).find_all{|x| x.year == yer}.count%>
   <%hash_of_month[arr2[number-1]]=Student.all.pluck(:dob).find_all{|x| x.month == number}.count%>
   <%number+=1%>
<%end%>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#new_student_form">
      New student form
</button>


<div class="row">
 <div class='col-md-6'>
   put the table inside 
   <!-- put the 6 columns allocated to the table -->
 </div>
 <div class='col-md-6'>
   put the form inside
   <!--uts the 6 columns allocated to the form i.e., right half of the page -->
 </div>
</div>




<div class="row" id="studentsList">
  <%@students.each do |student|%>
   <div class = "col-md-3">
     <div class="card">
     <img class="card-img-top" src="http://www.acfe.com/uploadedImages/ACFE_Website/Content/images/membership-certification/graduate-member.jpg" alt="Card image cap">
     <div class="card-block">
        <h4 class="card-title"><%= student.name%></h4>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted"><%=student.created_at%></small></p>
        <%= link_to "Register","/students/new",class: "btn btn-primary" %>
        <span class = "float-right">Number of courses taken :<%= student.courses.count%>  </span>
     </div>
     </div>
   </div>
  <%end%> 
</div>


  <div class="modal fade" id="new_student_form" tabindex="-1" role="dialog" aria-labelledby="new_student_formTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <!-- this is the modal body  heerere is the thing that  -->
      <div class="modal-body">
          <div id="student_form_errors"></div>
          <%= render 'students/form',student: @student%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
  </div>
  

<div class="row" >
<div class='col-md-8'>
<h1 >Students</h1>
<table class="table hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Major</th>
      <th>Courses</th>
      <th>datae of Birth</th>
    </tr>
  </thead>
<tbody>
  <% @students.each do |student| %>
      <tr>
        <td><a href="#" class="btn btn-default" data-target="#popupExternal" data-toggle="modal-popover"><%=student.name%></a></td>
        <td><%= student.email %></td>
        <td><%= student.major %></td>
        <td> <%student.courses.each do |course|%>
             <%=course.name%>
             <%end%></td>
        <td><%=student.dob%></td>
        <%#= link_to 'Show', student %>
        <%#= link_to 'Edit', edit_student_path(student) %>
        <%#= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class='col-md-4'>
   <%= render 'form',student: @student%>
</div>
</div>
<br/>
<%= link_to 'New Student', new_student_path %>
<%=column_chart(hash_of_year)%>
<%=column_chart(hash_of_month)%>
    <% url="https://gender-api.com/get?name=elizabeth&key=tFawQzmmGMKEctzAhm"%>
    <%response=HTTParty.get(url)%>
    <%=response.parsed_response%>
</div>    

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<% if(notice)%>
<div class="alert alert-success">
 <%= notice %>
 <script>
  $.growl.notice({message: "the record was successfully created!" });
 </script>
</div>
<%end%>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Email:</strong>
  <%=link_to @student.email,student_path(@student.id)%>
</p>

<p>
  <strong>Major:</strong>
  <%= @student.major %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @student.dob %>
</p>

Courses that are enrolled are as follows:
<ol>
<% if ! @student.courses.empty? %>
<% @student.courses.each do |course|%>
   <li><%=link_to course.name,course_path(course.id)%> -----
   	<%= link_to course.instructor.name,instructor_path(course.instructor.id)%>
   </li>
   <% end %>
<%else%>
<li>No courses have been enrolled yet </li>
<%end%>   
</ol>
<%#= link_to 'Edit', edit_student_path(@student) %> 
<%#= link_to 'Back', students_path %>
<script>  
  $.growl.notice({message: "the record was successfully created"});
</script>