config/routes.rb
Rails.application.routes.draw do
  resources :cities
  get 'students/check_email_presence'
  resources :courses
  resources :instructors
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :courses
  has_many :publications
  validates_presence_of :name,:email,:bio
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
    @instructor = Instructor.new
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
   respond_to do |format|
        format.js
        format.html
        format.json
   end 
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:name, :email, :bio)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for(@instructor, id: 'new_instructor_form', remote: true) do |form| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>
      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :instructor_name,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :instructor_email,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :instructor_bio,class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "submit",class: "btn btn-primary" %>
     <a href="#" id="student_reset">Reset</a>
  </div>

  
<% end %>

<script>
   var nameHandle = document.getElementById('instructor_name');
   var emailHandle = document.getElementById('instructor_email') 
</script>

app/views/instructors/_show.html.erb
<p>
  <html>
<body>
<form action="mailto:someone@example.com" method="post" enctype="text/plain">
<input type="hidden" name="#{@instructor.email}">
<input type="hidden" name="comment" size="5">
<input type="submit" value="sendemail">
</form>
</body>
</html></p>

<p>
  <strong>Bio:</strong>
  <%= @instructor.bio %>
</p>


<h2>Courses taught are as follows:</h2>
<% if ! (@instructor.courses.empty?)%>
 <% @instructor.courses.each do |course|%>
    <li><%= link_to course.name,course_path(course.id)%>-----   
        	<%=course.students.count%>students enrolled</li>
        	<%course.students.each do |student|%>
        	   <%=student.name%><br/>
        	<%end%>	
 <% end %>
<%else%>
    <h2>NO students enrolled for this course</h2>
<%end%>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
  <p id="notice"><%= notice %></p>
  <h1>Instructors</h1>
  <%data={}%> 
  <%total=0%>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/Ksbxik1FpB4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  <div class = 'row'>
  <div class = 'col-md-6'>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Bio</th>
        <th>Courses</th>
        <th colspan="3"></th>
      </tr>
    </thead>
     
          
    <tbody>
      <% @instructors.each do |instructor| %>
        <tr>
          <td><%=link_to instructor.name,instructor,remote: true%></td>
          <td><%=instructor.email%></td>
          <td><%= instructor.bio %></td>
          <td><%instructor.courses.each do |course|%>
              <%total+= course.students.length%>
              <%= course.name %>
              <%data[instructor.name]=total%>
              <%total=0%>
              <%end%>
              </td>  
          <%#= link_to 'Show', instructor %>
          <%#= link_to 'Edit', edit_instructor_path(instructor) %>
          <%#= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br/>
 </div>

 <div class= "col-md-6">
   <%= render 'form',instructor: @instructor %>
 </div>
</div>
 <%=pie_chart(data)%>


<div class="modal fade" id="instructorShowModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      
    </div>
  </div>
</div>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @instructor.name %>
</p>

<p>
  <html>
<body>
<form action="mailto:someone@example.com" method="post" enctype="text/plain">
<input type="hidden" name="#{@instructor.email}">
<input type="hidden" name="comment" size="5">
<input type="submit" value="sendemail">
</form>
</body>
</html></p>

<p>
  <strong>Bio:</strong>
  <%= @instructor.bio %>
</p>


<h2>Courses taught are as follows:</h2>
<% if ! (@instructor.courses.empty?)%>
 <% @instructor.courses.each do |course|%>
    <li><%= link_to course.name,course_path(course.id)%>-----   
        	<%=course.students.count%>students enrolled</li>
        	<%course.students.each do |student|%>
        	   <%=student.name%><br/>
        	<%end%>	
 <% end %>
<%else%>
    <h2>NO students enrolled for this course</h2>
<%end%>


<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/show.js.erb
$("#exampleModalLongTitle").html('<%=@instructor.name%>');
$('.modal-body').html('<%=escape_javascript(render 'show')%>');
$("#instructorShowModal").modal('show');