config/routes.rb
Rails.application.routes.draw do
  resources :cities
  get 'students/check_email_presence'
  resources :courses
  resources :instructors
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">CourseTracker</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>





  <!--this is for the row div -->
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
       <!--<li class="nav-item>
             <a href="" class ="nav-link">Students
             <span class= "badge badge-secondary">Students 100</span>  -->
        <!-- <a class="nav-link" href="#"> My Link </a> -->
        
       
      <li class="nav-item <%= controller.controller_name == 'students' ? 'active' : ''%>">
        <%= link_to students_path, class: "nav-link" do  %>
           Students<span class= "badge badge-secondary"><%= Student.count %></span>
        <% end%>
      </li>

      <li class="nav-item <%= controller.controller_name == 'instructors' ? 'active' : ''%>">
        <%= link_to "Instructors", instructors_path, class: "nav-link" %> 
      </li>
    
      <li class="nav-item dropdown <%= controller.controller_name == 'courses' ? 'active' : ''%>">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Courses
       </a>

      <%= link_to courses_path class: "nav-link" do %>
       Courses<span class="badge badge-secondary"><%=Course.count%></span>
      <%end%>



       <div>
       <nav aria-label = "breadcrumb">
         <ol class = "breadcrumb">
          <li class = "breadcrumb-item"><a href="/">Home</a></li>
          <li class = "breadcrumb-item">
             <%= link_to controller.controller_name.capitalize,"/#{controller.controller_name}"%></li>
          <% if(controller.action_name === "show")%>
              <%case controller.controller_name%>
                 <%when "students"%> 
                      <li class = "breadcrumb-item active" aria-current= "page"><%= @student.name%></li>   
                 <%when "instructors"%>
                      <li class  = "braedcrumb-item active" aria-current = "page"><%= @instructor.name%>
                 <% when "courses"%>
                      <li calss = "breadcrumb-item active" aria-current = "page"><%=@course.name%></li>
              <% end%>           
          <%else%>
               <li class = "breadcrumb-item active" aria-current = "page"><%=controller.action_name %></li>
          <% end%>
         </ol> 
       </nav>
       </div>   


       <div class="dropdown-menu" aria-labelledby="navbarDropdown">
         <% Course.all.each do |course| %>
           <!-- <a class="dropdown-item" href="#">Action</a> -->
           <%= link_to course.name, course, class: 'dropdown-item' %>
         <% end %>
       </div>
     </li>
    
   </ul>
   <form class="form-inline my-2 my-lg-0">
     <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
     <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
   </form>
 </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coursetrackingsystem</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>   
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src="/javascripts/jquery.growl.js" type="text/javascript"></script>
  <script src="/javascripts/chosen.jquery.js" type="text/javascript"></script>
  <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
  <link rel="stylesheet" type="text/css" href= "//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="/stylesheets/jquery.growl.css" rel="stylesheet" type="text/css" />
  <link href="/stylesheets/chosen.css" rel = "stylesheet" type="text/css" />
  <link href="/stylesheets/custom.css" rel = "stylesheet" type = "text/css"/>

</head>
<body>
  <div class='container'>
    <%= render 'layouts/nav'%>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz5Hdi3Wp3RA5YyatBe5k2PS8uDdtRHXTVf7OMGh1qSscMxwmd", style="width:100px;height:60px;">
    <%= link_to "Courses Catalogue",courses_path %>
    <%= link_to "Students Catalogue",students_path %>
    <%= link_to "Add a new Couse",new_course_path %>
    <%= link_to "add a new student",new_student_path%>
    <%= link_to "ADD a new instructor",new_instructor_path%>
    <%= link_to "INstructors catalogue",instructors_path%>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/uoRdrGLXDAY" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    <%= yield %>
  </div>
</body>
</html>